### ISSUE TITLE
Stand up a local postgres docker container with the skilldirectory schema

### ISSUE THREAD

**Issue by thebho** [maryvilledev/skilldirectoryinfra#38]

**Comment by dane-johnson** [comment]
Being worked on here https://github.com/maryvilledev/skilldirectoryinfra/tree/gorm_crud_demo

**Comment by dane-johnson** [comment]
Coming along here. Anything else needed before I close this?
https://github.com/maryvilledev/skilldirectoryinfra/tree/gorm_crud_demo/postgres
